### ISSUE TITLE
Deepmerge yaml array overriding

### ISSUE THREAD

**Issue by MostefaKamalLala** [cloudposse/terraform-provider-utils#368]
### Describe the Bug

If I deep merge for exemple:
yaml-1:
```yaml
root:
  key1:
    array:
       - key: yaml-1
         value: yaml-1
```
yaml-2:
```yaml
root:
  key1:
    array:
       - key: yaml-2
         value: yaml-2
```
but it is producing
resulting-yaml:
```yaml
root:
  key1:
    array:
       - key: yaml-2
         value: yaml-2
```

### Expected Behavior

resulting-yaml:
```yaml
root:
  key1:
    array:
       - key: yaml-1
         value: yaml-1
       - key: yaml-2
         value: yaml-2
```

### Steps to Reproduce

2 yaml as described using utils_deep_merge_yaml

### Environment

Terraform v1.6.2
on windows_386
+ provider registry.terraform.io/cloudposse/utils v1.18.0
